/**
 * Check if a conversation exchange is worth remembering
 * Filters out pleasantries, acknowledgments, and trivial messages
 * 
 * @param userMsg The user's message
 * @param assistantMsg The assistant's response
 * @returns True if worth remembering, false otherwise
 */
export function isWorthRemembering(userMsg: string, assistantMsg: string): boolean {
  const combined = `${userMsg} ${assistantMsg}`.toLowerCase().trim();
  
  // Skip empty exchanges
  if (!combined) return false;
  
  // Skip very short exchanges (< 50 chars) - likely trivial
  if (combined.length < 50) return false;
  
  // Skip if it's just pleasantries and acknowledgment patterns
  const pleasantries = [
    'thanks', 'thank you', 'ok', 'okay', 'got it', 
    'sounds good', 'will do', "you're welcome", 'sure',
    'great', 'nice', 'perfect', 'awesome'
  ];
  
  // Check if the entire message is just pleasantries
  const isJustPleasantries = pleasantries.some(p => 
    combined === p || combined === `${p}.` || combined === `${p}!`
  );
  
  if (isJustPleasantries) return false;
  
  // Check if mostly pleasantries and short
  if (combined.length < 100) {
    const hasPleasantry = pleasantries.some(p => combined.includes(p));
    if (hasPleasantry) return false;
  }
  
  // Skip standalone acknowledgments (just "ok", "thanks", etc.)
  const ackPattern = /^(ok|okay|got it|thanks|thank you|sure|yes|no|yep|nope)[\.\!\?]*$/i;
  if (ackPattern.test(userMsg.trim())) return false;

  if (isLowSignalConversationExchange(userMsg, assistantMsg)) return false;
  
  return true;
}

const DURABLE_SIGNAL_PATTERNS = [
  /\bhttps?:\/\/\S+/i,
  /\b[\w.-]+@[\w.-]+\.\w+\b/,
  /\bport\s+\d{2,5}\b/i,
  /\b\d{2,5}\/tcp\b/i,
  /\b(?:proj|sum|mem|ops|inc|task|ticket|issue)(?:[-_][a-z0-9]{2,}|\d{2,})\b/i,
  /\b(?:docker|kubectl|systemctl|npm|pnpm|uv|pytest|curl|ssh|scp|git)\b/i,
  /\/plugins\/[A-Za-z0-9/_-]+/i,
  /(?:^|\s)(?:~\/|\/[A-Za-z0-9._-]+\/|\.[/A-Za-z0-9._-]+)/,
  /`[^`]+`/,
  /\b(?:registerHttpRoute|registerCommand|before_prompt_build|sessionKey)\b/,
  /\b(?:MEMOS|OPENAI|GRAPHITI)_[A-Z0-9_]+\b/,
  /\b(?:TypeError|ReferenceError|SyntaxError|RangeError|Error:)\b/,
  /\b(?:metrics endpoint|http route|auth field|project id|api key)\b/i,
  /\b(?:decided|decision|policy|requirement|procedure|runbook|credential|password|token|key|endpoint|url|rollback|incident|deploy|deployment)\b/i,
];

const TRANSIENT_STATUS_PATTERNS = [
  /\bstanding by\b/i,
  /\bstill testing\b/i,
  /\bwill do\b/i,
  /\bchecking(?: now)?\b/i,
  /\blooking into (?:it|this)\b/i,
  /\binvestigating\b/i,
  /\bworking on (?:it|this)\b/i,
  /\bneed to write (?:one|two|more) messages\b/i,
  /\bsee if .*?\b(?:works?|working)\b/i,
  /\bcontext monitor(?:ing)? is working\b/i,
  /\bdone\b/i,
  /\bcompleted\b/i,
  /\bok(?:ay)?\b/i,
  /\bgot it\b/i,
  /\backnowledged\b/i,
  /\bnoted\b/i,
  /\bready when you are\b/i,
  /\bbe right back\b/i,
];

const META_MEMORY_PATTERNS = [
  /\(session bootstrap\)/i,
  /\bsession startup\b/i,
  /\bmemos-auto-capture\b/i,
  /\bsession context was generated by\b/i,
  /\bthe assistant runs the session startup sequence\b/i,
  /\bconfirms? that the session startup is working\b/i,
  /\bstartup is working\b/i,
];

const GENERIC_TESTING_CHATTER_PATTERNS = [
  /\bstill testing\b/i,
  /\bneed to write (?:one|two|more) messages\b/i,
  /\bsee if .*?\b(?:works?|working)\b/i,
  /\bcontext monitor(?:ing)? is working\b/i,
];

const LOW_SIGNAL_FACT_PATTERNS = [
  /\bstanding by\b/i,
  /\bchecking(?: now)?\b/i,
  /\bwill do\b/i,
  /\blooking into (?:it|this)\b/i,
  /\bworking on (?:it|this)\b/i,
  /\binvestigating\b/i,
  /\bavailable to help\b/i,
  /\bready to assist\b/i,
  /\bawaiting instructions\b/i,
  /\bdone\b/i,
  /\backnowledged\b/i,
  /\bnoted\b/i,
  ...META_MEMORY_PATTERNS,
];

export function isMetaMemoryNoise(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) {
    return false;
  }
  return META_MEMORY_PATTERNS.some((pattern) => pattern.test(trimmed));
}

export function containsDurableSignal(text: string): boolean {
  const trimmed = text.trim();
  if (!trimmed) {
    return false;
  }
  return DURABLE_SIGNAL_PATTERNS.some((pattern) => pattern.test(trimmed));
}

export function isLowSignalConversationExchange(userMsg: string, assistantMsg: string): boolean {
  const normalizedUser = userMsg.trim();
  const normalizedAssistant = assistantMsg.trim();
  const combined = `${normalizedUser}\n${normalizedAssistant}`.trim();
  if (!combined) {
    return true;
  }

  if (isMetaMemoryNoise(combined)) {
    return true;
  }

  if (containsDurableSignal(combined)) {
    return false;
  }

  if (GENERIC_TESTING_CHATTER_PATTERNS.some((pattern) => pattern.test(combined))) {
    return true;
  }

  const shortExchange = combined.length < 180;
  if (!shortExchange) {
    return false;
  }

  return TRANSIENT_STATUS_PATTERNS.some((pattern) => pattern.test(combined));
}

export function isLowSignalFact(factText: string): boolean {
  const trimmed = factText.trim();
  if (!trimmed) {
    return false;
  }

  if (isMetaMemoryNoise(trimmed)) {
    return true;
  }

  if (containsDurableSignal(trimmed)) {
    return false;
  }

  if (trimmed.length > 180) {
    return false;
  }

  return LOW_SIGNAL_FACT_PATTERNS.some((pattern) => pattern.test(trimmed));
}

const DEFAULT_CAPTURE_MAX_MESSAGE_CHARS = 600;
const TOOL_DUMP_MIN_CLEAN_RATIO = 0.35;
const TOOL_DUMP_MIN_REMAINING_CHARS = 80;

const SUMMARY_MARKERS = [
  /##\s*Executive Memory Summary/i,
  /\bSummary ID:\s*sum_/i,
];

const SYNTHETIC_SESSION_MARKERS = [
  /Continue where you left off\. The previous model attempt failed or timed out\./i,
  /\(session bootstrap\)/i,
  /\bsession startup\b/i,
  /\bmemos-auto-capture\b/i,
];

const TOOL_DUMP_MARKERS = [
  /Conversation info \(untrusted metadata\):/i,
  /HTTP\/1\.1/i,
  /\b(?:GET|POST|PUT|PATCH|DELETE)\s+\/[A-Za-z0-9/_-]+/i,
  /```/,
];

function getCaptureMaxMessageChars(): number {
  const raw = Number(process.env.MEMOS_CAPTURE_MAX_MESSAGE_CHARS || DEFAULT_CAPTURE_MAX_MESSAGE_CHARS);
  if (!Number.isFinite(raw) || raw < 80) {
    return DEFAULT_CAPTURE_MAX_MESSAGE_CHARS;
  }
  return Math.floor(raw);
}

function truncateForCapture(content: string, maxChars: number): string {
  if (content.length <= maxChars) {
    return content;
  }

  const truncated = content.slice(0, Math.max(0, maxChars - 3)).trimEnd();
  return `${truncated}...`;
}

function hasMarker(content: string, patterns: RegExp[]): boolean {
  return patterns.some(pattern => pattern.test(content));
}

function stripCaptureNoise(content: string): string {
  return content
    .replace(/```[\s\S]*?```/g, '\n')
    .replace(/Conversation info \(untrusted metadata\):/gi, ' ')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export function shouldSkipMessageForCapture(content: string): boolean {
  return hasMarker(content, [...SUMMARY_MARKERS, ...SYNTHETIC_SESSION_MARKERS]);
}

export function sanitizeMessageForCapture(content: string): string {
  const cleaned = stripCaptureNoise(content);
  const maxChars = getCaptureMaxMessageChars();
  return truncateForCapture(cleaned, maxChars);
}

export function looksLikeToolDump(content: string, cleaned: string): boolean {
  if (!hasMarker(content, TOOL_DUMP_MARKERS)) {
    return false;
  }

  if (!cleaned) {
    return true;
  }

  if (cleaned.length < TOOL_DUMP_MIN_REMAINING_CHARS) {
    return true;
  }

  return cleaned.length / Math.max(content.length, 1) < TOOL_DUMP_MIN_CLEAN_RATIO;
}

export function prepareExchangeForCapture(
  userMsg: string,
  assistantMsg: string
): {
  userMsg: string;
  assistantMsg: string;
  skip: boolean;
  reason?: string;
} {
  if (shouldSkipMessageForCapture(userMsg) || shouldSkipMessageForCapture(assistantMsg)) {
    return {
      userMsg: '',
      assistantMsg: '',
      skip: true,
      reason: 'summary_context',
    };
  }

  const cleanedUser = sanitizeMessageForCapture(userMsg);
  const cleanedAssistant = sanitizeMessageForCapture(assistantMsg);

  if (looksLikeToolDump(userMsg, cleanedUser) || looksLikeToolDump(assistantMsg, cleanedAssistant)) {
    return {
      userMsg: '',
      assistantMsg: '',
      skip: true,
      reason: 'tool_dump',
    };
  }

  if (!cleanedUser || !cleanedAssistant) {
    return {
      userMsg: '',
      assistantMsg: '',
      skip: true,
      reason: 'empty_after_sanitize',
    };
  }

  return {
    userMsg: cleanedUser,
    assistantMsg: cleanedAssistant,
    skip: false,
  };
}

export function shouldSkipMessageForRecall(role: string, content: string): boolean {
  if (role !== 'user' && role !== 'assistant') {
    return true;
  }

  if (hasMarker(content, [...SUMMARY_MARKERS, ...SYNTHETIC_SESSION_MARKERS])) {
    return true;
  }

  const cleaned = sanitizeMessageForCapture(content);
  if (!cleaned) {
    return true;
  }

  return looksLikeToolDump(content, cleaned);
}

export function prepareMessagesForRecall(
  messages: Array<{ role: string; content: string }>,
  limit: number = 3
): Array<{ role: 'user' | 'assistant'; content: string }> {
  const prepared = messages.flatMap(message => {
    if (!message || typeof message.content !== 'string' || typeof message.role !== 'string') {
      return [];
    }

    if (shouldSkipMessageForRecall(message.role, message.content)) {
      return [];
    }

    const cleaned = sanitizeMessageForCapture(message.content);
    if (!cleaned) {
      return [];
    }

    return [{
      role: message.role as 'user' | 'assistant',
      content: cleaned,
    }];
  });

  return prepared.slice(-Math.max(1, limit));
}

/**
 * Extract the last user and assistant messages from context
 * @param messages Array of messages
 * @returns Object with lastUser and lastAssistant messages
 */
export function getLastExchange(messages: Array<{ role: string; content: string }>): {
  lastUser: string;
  lastAssistant: string;
} {
  // Find last user message
  let lastUser = '';
  let lastAssistant = '';
  
  // Iterate backwards to find the last user-assistant exchange
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i];
    
    if (msg.role === 'assistant' && !lastAssistant) {
      lastAssistant = msg.content;
    } else if (msg.role === 'user' && !lastUser) {
      lastUser = msg.content;
    }
    
    // If we found both, break
    if (lastUser && lastAssistant) break;
  }
  
  return { lastUser, lastAssistant };
}

/**
 * Build episode content from user and assistant messages
 * @param lastUser The last user message
 * @param lastAssistant The last assistant message
 * @returns Formatted episode content
 */
export function buildEpisodeContent(lastUser: string, lastAssistant: string): string {
  return `USER: ${lastUser}\nASSISTANT: ${lastAssistant}`.trim();
}
